# 异常处理

## 异常概述与异常体系结构
Java程序在执行过程中所发生的异常事件可以分为两类：  
- Error：Java虚拟机无法解决的严重问题。如JVM系统内部错误、资源耗尽等严重现象。比如：StackOverflowError、OOM。一般不编写针对性的代码进行处理  

```java
public class ErrorTest {
    public static void main(String[] args) {
        // 1. 栈溢出：java.lang.StackOverflowError
        // main(args);

        // 2. 堆溢出：java.lang.OutOfMemeryError
        // Integer[] arr = new Integer[1024 * 2024 * 1024];
    }
}
```

- Exception：其他因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如：空指针访问、试图读取不存在的文件、网络连接中断、数组角标越界  

异常体系结构  
java.lang.Throwable  
- java.lang.Error：一般不编写针对性的代码进行处理  
- java.lang.Exception：可以进行异常的处理  
    - 编译时异常（checked）
        - IOException
            - FileNotFoundException
    - 运行时异常（unchecked）
        - NullPointException
        - ArrayIndexOutOfBoundsException
        - ClassCastException
        - NumberFormatException
        - InputMismatchException
        - ArithmeticException

面试题：常见的异常都有哪些？举例说明

## 常见异常
```java
import java.io.File;
import java.io.FileInputStream;
import java.util.Date;
import java.util.Scanner;

public class ExceptionTest {
    //*******************以下是编译时异常*******************
    public void test7() {
        File file = new File("hello.txt");
        FileInputStream fis = new FileInputStream(file); // Unhandled exception type FileNotFoundException
        
        int data = fis.read(); // Unhandled exception type IOException
        while (data != -1) {
            System.out.println((char) data);
            data = fis.read(); // Unhandled exception type IOException
        }
        fis.close(); // Unhandled exception type IOException
    }
    
    //*******************以下是运行时异常*******************
    // NullPointException
    public void test1() {
        // int[] arr = null;
        // System.out.println(arr[3]);
        String str = null;
        System.out.println(str.charAt(0));
    }

    // IndexOutOfBoundsException
    public void test2() {
        // ArrayIndexOutOfBoundsException
        // int[] arr = new int[10];
        // System.out.println(arr[10]);
        // StringIndexOutOfBoundsException
        String str = "abc";
        System.out.println(str.charAt(3));
    }

    // ClassCastException 类型转换异常
    public void test3() {
        Object obj = new Date();
        String str = (String) obj;
    }

    // NumberFormatException
    public void test4() {
        String str = "abc";
        int num = Integer.parseInt(str);
    }
    
    // InputMismatchException
    public void test5() {
        Scanner scanner = new Scanner(System.in);
        int score = scanner.nextInt(); // 终端输入abc
        System.out.println(score);
        scanner.close();
    }

    // ArithmeticException 算术异常
    public void test6() {
        int a = 10;
        int b = 0;
        System.out.println(a/b);
    }   
    public static void main(String[] args) {
        ExceptionTest test = new ExceptionTest();
        test.test6();
    }
}
```
## 异常处理机制一：try-catch-finally

## 异常处理机制二：throws

## 手动抛出异常：throw

## 用户自定义异常类